/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 92da7fc0be2469f3d7ae03cc2180a989)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	HN_DATA: Fetcher /* super-hn-data */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
